### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sugarless-cha** [sugarless-cha/public#13]
- [x] 概念設計 トップダウン
- [x] 概念設計 ボトムアップ
- [x] 練習問題　単一表
- [x] 練習問題　副問い合わせ
- [x] 1日目用のDB/ 初期データ
- [x] 2日目用のDB/ 初期データ
- [x] indexチューニング課題
- [x] SQLチューニング課題
- [x] DB設計　各フィールドの日本語名 ( 練習問題のテーブル名、列名を揃える ) 
- [x] init_x のパターンを x 2　追加する 
- [x] チューニング問題を正規化を崩した場合の table 構造を作ってみる。 実際にデータを移行して analyze 結果を確認
- [x] db拡張課題 https://github.com/sugarless-cha/public/issues/19
- [x] 練習問題　結合 ( 10問 )  https://github.com/sugarless-cha/public/issues/17
- [x] 練習問題　単一表 https://github.com/sugarless-cha/public/issues/15
- [x] 算術関数( 9問) https://github.com/sugarless-cha/public/issues/11
- [x] 文字列関数(10問) 　https://github.com/sugarless-cha/public/issues/12
- [x] 練習問題 トランザクション https://github.com/sugarless-cha/public/issues/20
- [x] 練習問題 window関数  https://github.com/sugarless-cha/public/issues/21
- [x] analyze 結果の解説  https://github.com/sugarless-cha/public/issues/22

作業実績集計  https://github.com/sugarless-cha/public/issues/5

**Comment by sugarless-cha** [comment]
## トップダウンアプローチ

A社は文具の専門店を近畿地方を中心に20店舗展開する企業。
販路を拡大するため店舗だけではなく、文具のECサイトを立ち上げて個人や法人向けに文具を直接販売することとなった。

#### 要件
- 商品にはそれぞれ製造元のメーカがある
- 一つの商品はかならず一つのメーカから仕入れを行っている
- 利用者は購入サイトで会員登録すると文具を購入することができる
- 利用者は購入サイトで商品と、数量を選んで購入する
- 購入サイトには買い物かご機能があり、利用者は一度に複数の商品を数量を指定して購入することができる
- 決済機能は外部サービスを利用しているため、当システムでは特に意識する必要はない

**Comment by sugarless-cha** [comment]
- [ ] SQL結果行数を追加　(Mi)
- [ ] SQLや結果行数を除いた(回答なし) 版を作成
- [ ] small.ddl, large_ddl ?
- [ ] large の作成手順
- [ ] explain analyze の説明。改善させたパターンを追加
- [ ] あわせてSQLチューニングの導入説明を追加 


### 準備
- DB構築

### 練習問題 
- 練習問題 概念設計
- 練習問題 文字列関数
- 練習問題 算術関数
- 練習問題 副問い合わせ
- 練習問題 単一表
- 練習問題 結合
- 練習問題 window関数
- 練習問題 トランザクション

### 総合演習
- 総合演習 データベース拡張
- 総合演習 explain analyze 解説
- 総合演習 SQLチューニング (SQLの見直し、インデックス作成、
